apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels: 
    app: prometheus1
spec:
  ports:
      - nodePort: 30852
        port:  9090
        targetPort: 9090
  selector:
    app: prometheus1
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pv-claim
  labels:
    app: prometheus1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
kind:  ConfigMap
apiVersion:  v1
metadata:
   name:  prometheus-script
data:
    prometheus.yml:  |
              global:
                   scrap_interval:      15s
                   evaluation_interval:   15s
              altering:
                    altermanagers:
                    - static_configs:
                       -  targets:
              rule_files:
              scrap_configs:
                     -  job_name:   'prometheus-node'
                        static_configs:
                        -  targets:  ['localhost:9090']
                     -  job_name:   'testing_node'
                        static_configs:
                        -  targets:  ['192.168.99.103:9100']
                           labels:
                                     app:  'prometheus1'
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: prometheuspod
  labels:
    app: prometheus1
spec:
  selector:
    matchLabels:
      app: prometheus1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus1
    spec:
      containers:
      - image:   vish1234/prometheus:p2
        name:  prometheus1
        ports:
        - containerPort: 9090
          name: prometheus1
        volumeMounts:
        - name: prom-script
          mountPath:   /etc/prometheus/prometheus.yml
          subPath:  prometheus.yml
        - name:  prometheus-persistent-storage
          mountPath:  /etc/prometheus
      volumes:
      - name: prometheus-persistent-storage
        persistentVolumeClaim:
          claimName: prometheus-pv-claim
      - name:  prom-script
        configMap:
               name:  prometheus-script
               defaultMode:  0744
